package com.flaremars.classmanagers.model;

/**
 * 定义所有Fragment代表符号
 */
public enum FragmentConst {
    FRAGMENT_CLASS_CENTER,
    FRAGMENT_ANNOUNCEMENTS_LIST,
    FRAGMENT_CONTACTS,
    FRAGMENT_FILES,
    FRAGMENT_ALBUMS,
    FRAGMENT_EXCEL_MODELS,
    FRAGMENT_CREATE_ANNOUNCEMENT,
    FRAGMENT_PERSONAL_CENTER,
    FRAGMENT_OTHER_CLASS_MESSAGE,
    FRAGMENT_DOWNLOADED_FILES,
    FRAGMENT_SETTING,
    FRAGMENT_NOTICE_GROUPS,
    FRAGMENT_FILL_EXCEL,
    FRAGMENT_CREATE_CLASS,
    FRAGMENT_NOTICE_DETAIL,
    FRAGMENT_PHOTOS,
    FRAGMENT_FEEDBACK_DETAIL
}
